# Generated by Django 4.2.7 on 2023-11-29 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_question_options_question_optionsa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(blank=True, choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D'), (4, 'E')], max_length=255, null=True),
        ),
    ]
